main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login$', views.login, name="login"),
    url(r'^register$', views.register, name="register"),
]

my_website/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from main import views as main_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', main_view.index, name="index"),
    # url(r'^authuser/', include('authuser.urls')),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^cms/', include('cms.urls')),
    # url(r'^tally/', include('tally.urls')),
    # url(r'^project/', include('project.urls')),
    url(r'^main/', include('main.urls', namespace="main")),
]

authuser/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# Create your models here.

cms/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User, Group

# Create your models here.
class AuthUser(User):
    pass

project/models.py
from django.db import models

# Create your models here.

tally/models.py
from django.db import models

# Create your models here.
# class Consumption(models.Model):
# 	consum_type = models.CharField(version_name="", null=True)
# 	account = models.FloatField(version_name="", null=True)

authuser/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render

# Create your views here.

cms/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render, render_to_response

# Create your views here.

def index(request):
    content = {
        "info": "success"
    }
    return render(
        request, "index.html", content
    )

def login(request):
    content={
        "info": "success"
    }
    return render(request, "main/login.html", content)

def register(request):
    content={
        "info": "success"
    }
    return render(request, "main/register.html", content)

project/views.py
from django.shortcuts import render

# Create your views here.

tally/views.py
from django.shortcuts import render

# Create your views here.

templates/authuser/login.html
<!DOCTYPE html>
<html>
    <meta charset="utf-8">
    <body >
        <div>
        <p>登陆</p>
        </div>
        <form methon="POST" id="login_form">
            <input type="text" name="username">
            <br/>
            <input type="text" name="password">
            <br/>
            <input type="submit" value="登陆">
        </form>
        <div>
            <a href="">立即注册</a>
            <a href="">忘记密码?</a>
        </div>
        <p></p>
    </body>
</html>

templates/cms/cms_index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
    
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <!-- <meta charset="utf-8" /> -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
    <!-- <title>Page Title</title> -->
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
    <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css" /> -->
    <link href="/static/main/css/main.css" rel="stylesheet" type="text/css" charset="utf-8">
    <!-- <link href="static/css/main.css" rel="stylesheet" type="text/css" charset="utf-8"> -->
    <!-- <script src="/static/js/main.js"></script> -->
</head>
<body >
    <div class="index-head">
        <div class="nav">
            <ul class="head-ul-left">
                <li><a href="">CMS</a></li>
                <li><a href="">Blog</a></li>
                <li><a href="">Project</a></li>
                <li><a href="">Tally</a></li>
            </ul>
            <ul class="head-ul-right">
                <li><a href="/main/register">Register</a></li>
                <li><a href="{% url 'main:login' %}">Login</a></li>
            </ul>
        </div>
    </div>
    <div id="index-middle">
        <div class="introduce">
            <p class="introduce-show">Introduce</p><br/>
            <p class="introduce-detailed ">NAME:CSATAI</p>
            <p class="introduce-detailed ">ADDRESS:ChangSha</p>
            <p class="introduce-detailed ">PROFESSION:Python</p>
        </div>
    </div>
    <div id="index-footer"></div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>用户登陆</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css" /> -->
    <!-- <script src="main.js"></script> -->
</head>
<body>
    <div class="">
        <p>用户登陆</p>
        <form>
            <input type="text" name="">
            <input type="text" name="">
            <input type="button" name="">
        </form>
        <a>立即注册</a> <a>忘记密码?</a>
    </div>
</body>
</html>

templates/main/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>用户登陆</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css" /> -->
    <!-- <script src="main.js"></script> -->
</head>
<body>
    <div class="">
        <p>用户登陆</p>
        <form>
            <input type="text" name="">
            <input type="text" name="">
            <input type="button" name="">
        </form>
        <a>立即注册</a> <a>忘记密码?</a>
    </div>
</body>
</html>